-- MySQL Script generated by MySQL Workbench
-- Wed May  8 18:39:11 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema iosProd
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `iosProd` ;

-- -----------------------------------------------------
-- Schema iosProd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `iosProd` DEFAULT CHARACTER SET utf8 ;
USE `iosProd` ;

-- -----------------------------------------------------
-- Table `iosProd`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iosProd`.`Users` ;

CREATE TABLE IF NOT EXISTS `iosProd`.`Users` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(50) NOT NULL,
  `OrganizationID` INT NULL,
  `HashedPassword` CHAR(64) NOT NULL,
  `UserStatus` INT NOT NULL,
  `ImageLocation` VARCHAR(500) NULL,
  `FullName` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID`, `Username`),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iosProd`.`Organizations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iosProd`.`Organizations` ;

CREATE TABLE IF NOT EXISTS `iosProd`.`Organizations` (
  `OrganizationID` INT NOT NULL AUTO_INCREMENT,
  `OrganizationName` VARCHAR(50) NOT NULL,
  `OrganizationPassword` CHAR(64) NOT NULL,
  `OrganizationDescription` VARCHAR(240) NULL,
  PRIMARY KEY (`OrganizationID`),
  UNIQUE INDEX `OrganizationName_UNIQUE` (`OrganizationName` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iosProd`.`Projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iosProd`.`Projects` ;

CREATE TABLE IF NOT EXISTS `iosProd`.`Projects` (
  `ProjectID` INT NOT NULL AUTO_INCREMENT,
  `ProjectName` VARCHAR(45) NOT NULL,
  `ProjectDescription` VARCHAR(1000) NULL,
  `OrganizationID` INT NULL,
  `DateStarted` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LeaderID` INT NOT NULL,
  PRIMARY KEY (`ProjectID`),
  INDEX `fk_Projects_Organization1_idx` (`OrganizationID` ASC),
  INDEX `fk_Projects_Users1_idx` (`LeaderID` ASC),
  UNIQUE INDEX `DateStarted_UNIQUE` (`DateStarted` ASC),
  CONSTRAINT `fk_Projects_Organization1`
    FOREIGN KEY (`OrganizationID`)
    REFERENCES `iosProd`.`Organizations` (`OrganizationID`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Projects_Users1`
    FOREIGN KEY (`LeaderID`)
    REFERENCES `iosProd`.`Users` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iosProd`.`Uploads`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iosProd`.`Uploads` ;

CREATE TABLE IF NOT EXISTS `iosProd`.`Uploads` (
  `UploadID` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(50) NOT NULL,
  `ProjectID` INT NOT NULL,
  `DateUploaded` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UploaderID` INT NOT NULL,
  `UploadContent` TEXT NULL,
  PRIMARY KEY (`UploadID`),
  INDEX `fk_Uploads_Projects1_idx` (`ProjectID` ASC),
  INDEX `fk_Uploads_Users1_idx` (`UploaderID` ASC),
  CONSTRAINT `fk_Uploads_Projects1`
    FOREIGN KEY (`ProjectID`)
    REFERENCES `iosProd`.`Projects` (`ProjectID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uploads_Users1`
    FOREIGN KEY (`UploaderID`)
    REFERENCES `iosProd`.`Users` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iosProd`.`MediaUploads`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iosProd`.`MediaUploads` ;

CREATE TABLE IF NOT EXISTS `iosProd`.`MediaUploads` (
  `UploadID` INT NOT NULL,
  `MediaType` INT NOT NULL,
  `MediaLocation` VARCHAR(500) NULL,
  `MediaID` INT NOT NULL,
  PRIMARY KEY (`UploadID`, `MediaID`),
  INDEX `fk_MediaUploads_Uploads_idx` (`UploadID` ASC),
  CONSTRAINT `fk_MediaUploads_Uploads`
    FOREIGN KEY (`UploadID`)
    REFERENCES `iosProd`.`Uploads` (`UploadID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iosProd`.`Shares`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iosProd`.`Shares` ;

CREATE TABLE IF NOT EXISTS `iosProd`.`Shares` (
  `ProjectID` INT NOT NULL,
  `UserID` INT NOT NULL,
  `IsContributor` TINYINT NOT NULL,
  PRIMARY KEY (`ProjectID`, `UserID`),
  INDEX `fk_Shares_Projects1_idx` (`ProjectID` ASC),
  INDEX `fk_Shares_Users1_idx` (`UserID` ASC),
  CONSTRAINT `fk_Shares_Projects1`
    FOREIGN KEY (`ProjectID`)
    REFERENCES `iosProd`.`Projects` (`ProjectID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Shares_Users1`
    FOREIGN KEY (`UserID`)
    REFERENCES `iosProd`.`Users` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iosProd`.`Editors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iosProd`.`Editors` ;

CREATE TABLE IF NOT EXISTS `iosProd`.`Editors` (
  `UserID` INT NOT NULL,
  `OrganizationID` INT NOT NULL,
  PRIMARY KEY (`UserID`),
  INDEX `fk_Editors_Organization1_idx` (`OrganizationID` ASC),
  CONSTRAINT `fk_Editors_Users1`
    FOREIGN KEY (`UserID`)
    REFERENCES `iosProd`.`Users` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Editors_Organization1`
    FOREIGN KEY (`OrganizationID`)
    REFERENCES `iosProd`.`Organizations` (`OrganizationID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iosProd`.`EditorNotes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iosProd`.`EditorNotes` ;

CREATE TABLE IF NOT EXISTS `iosProd`.`EditorNotes` (
  `UploadID` INT NOT NULL,
  `NoteID` INT NOT NULL,
  `NoteContent` VARCHAR(5000) NULL,
  `EditorID` INT NOT NULL,
  PRIMARY KEY (`UploadID`, `NoteID`),
  INDEX `fk_EditorNotes_Editors1_idx` (`EditorID` ASC),
  INDEX `fk_EditorNotes_Uploads1_idx` (`UploadID` ASC),
  CONSTRAINT `fk_EditorNotes_Editors1`
    FOREIGN KEY (`EditorID`)
    REFERENCES `iosProd`.`Editors` (`UserID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EditorNotes_Uploads1`
    FOREIGN KEY (`UploadID`)
    REFERENCES `iosProd`.`Uploads` (`UploadID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
