# Uncomment the next line to define a global platform for your project
platform :ios, '12.2'

target 'firebaseAuth' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Firebase/Core'
pod ‘Firebase/Auth’

  # Pods for firebaseAuth

  target 'firebaseAuthTests' do
    inherit! :search_paths

    # Pods for testing
  end

  target 'firebaseAuthUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
