-- MySQL Script generated by MySQL Workbench
-- Wed May  1 15:03:05 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(70) NOT NULL,
  `OrganizationID` INT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `UserStatus` INT NOT NULL,
  `ImageLocation` VARCHAR(500) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Organization` (
  `OrganizationID` INT NOT NULL AUTO_INCREMENT,
  `OrganizationName` INT NOT NULL,
  `OrganizationPassword` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`OrganizationID`),
  UNIQUE INDEX `OrganizationName_UNIQUE` (`OrganizationName` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Projects` (
  `ProjectID` INT NOT NULL AUTO_INCREMENT,
  `ProjectName` VARCHAR(45) NOT NULL,
  `ProjectDescription` VARCHAR(1000) NULL,
  `OrganizationID` INT NULL,
  `DateStarted` DATETIME NOT NULL,
  `LeaderID` INT NOT NULL,
  PRIMARY KEY (`ProjectID`),
  INDEX `fk_Projects_Organization1_idx` (`OrganizationID` ASC) VISIBLE,
  INDEX `fk_Projects_Users1_idx` (`LeaderID` ASC) VISIBLE,
  CONSTRAINT `fk_Projects_Organization1`
    FOREIGN KEY (`OrganizationID`)
    REFERENCES `mydb`.`Organization` (`OrganizationID`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Projects_Users1`
    FOREIGN KEY (`LeaderID`)
    REFERENCES `mydb`.`Users` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Uploads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Uploads` (
  `UploadID` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(50) NOT NULL,
  `ProjectID` INT NOT NULL,
  `DateUploaded` DATETIME NOT NULL,
  `UploaderID` INT NOT NULL,
  `UploadContent` TEXT NULL,
  PRIMARY KEY (`UploadID`),
  INDEX `fk_Uploads_Projects1_idx` (`ProjectID` ASC) VISIBLE,
  INDEX `fk_Uploads_Users1_idx` (`UploaderID` ASC) VISIBLE,
  CONSTRAINT `fk_Uploads_Projects1`
    FOREIGN KEY (`ProjectID`)
    REFERENCES `mydb`.`Projects` (`ProjectID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uploads_Users1`
    FOREIGN KEY (`UploaderID`)
    REFERENCES `mydb`.`Users` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MediaUploads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MediaUploads` (
  `UploadID` INT NOT NULL,
  `MediaType` INT NOT NULL,
  `MediaLocation` VARCHAR(500) NULL,
  `MediaID` INT NOT NULL,
  PRIMARY KEY (`UploadID`, `MediaID`),
  INDEX `fk_MediaUploads_Uploads_idx` (`UploadID` ASC) VISIBLE,
  CONSTRAINT `fk_MediaUploads_Uploads`
    FOREIGN KEY (`UploadID`)
    REFERENCES `mydb`.`Uploads` (`UploadID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Shares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Shares` (
  `ProjectID` INT NOT NULL,
  `UserID` INT NOT NULL,
  `IsContributor` TINYINT NOT NULL,
  PRIMARY KEY (`ProjectID`, `UserID`),
  INDEX `fk_Shares_Projects1_idx` (`ProjectID` ASC) VISIBLE,
  INDEX `fk_Shares_Users1_idx` (`UserID` ASC) VISIBLE,
  CONSTRAINT `fk_Shares_Projects1`
    FOREIGN KEY (`ProjectID`)
    REFERENCES `mydb`.`Projects` (`ProjectID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Shares_Users1`
    FOREIGN KEY (`UserID`)
    REFERENCES `mydb`.`Users` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Editors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Editors` (
  `UserID` INT NOT NULL,
  `OrganizationID` INT NOT NULL,
  PRIMARY KEY (`UserID`),
  INDEX `fk_Editors_Users1_idx` (`UserID` ASC) VISIBLE,
  INDEX `fk_Editors_Organization1_idx` (`OrganizationID` ASC) VISIBLE,
  CONSTRAINT `fk_Editors_Users1`
    FOREIGN KEY (`UserID`)
    REFERENCES `mydb`.`Users` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Editors_Organization1`
    FOREIGN KEY (`OrganizationID`)
    REFERENCES `mydb`.`Organization` (`OrganizationID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EditorNotes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EditorNotes` (
  `UploadID` INT NOT NULL,
  `NoteID` INT NOT NULL,
  `NoteContent` VARCHAR(5000) NULL,
  `EditorID` INT NOT NULL,
  PRIMARY KEY (`UploadID`, `NoteID`),
  INDEX `fk_EditorNotes_Editors1_idx` (`EditorID` ASC) VISIBLE,
  INDEX `fk_EditorNotes_Uploads1_idx` (`UploadID` ASC) VISIBLE,
  CONSTRAINT `fk_EditorNotes_Editors1`
    FOREIGN KEY (`EditorID`)
    REFERENCES `mydb`.`Editors` (`UserID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EditorNotes_Uploads1`
    FOREIGN KEY (`UploadID`)
    REFERENCES `mydb`.`Uploads` (`UploadID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
